//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prac3_MVC.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Book", Namespace="http://schemas.datacontract.org/2004/07/Prac3")]
    [System.SerializableAttribute()]
    public partial class Book : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AuthorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal PriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StockField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int YearField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Author {
            get {
                return this.AuthorField;
            }
            set {
                if ((object.ReferenceEquals(this.AuthorField, value) != true)) {
                    this.AuthorField = value;
                    this.RaisePropertyChanged("Author");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Num {
            get {
                return this.NumField;
            }
            set {
                if ((this.NumField.Equals(value) != true)) {
                    this.NumField = value;
                    this.RaisePropertyChanged("Num");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Price {
            get {
                return this.PriceField;
            }
            set {
                if ((this.PriceField.Equals(value) != true)) {
                    this.PriceField = value;
                    this.RaisePropertyChanged("Price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Stock {
            get {
                return this.StockField;
            }
            set {
                if ((this.StockField.Equals(value) != true)) {
                    this.StockField = value;
                    this.RaisePropertyChanged("Stock");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Year {
            get {
                return this.YearField;
            }
            set {
                if ((this.YearField.Equals(value) != true)) {
                    this.YearField = value;
                    this.RaisePropertyChanged("Year");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IBookService")]
    public interface IBookService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookService/ReadBook", ReplyAction="http://tempuri.org/IBookService/ReadBookResponse")]
        Prac3_MVC.ServiceReference1.Book[] ReadBook(string path);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookService/ReadBook", ReplyAction="http://tempuri.org/IBookService/ReadBookResponse")]
        System.Threading.Tasks.Task<Prac3_MVC.ServiceReference1.Book[]> ReadBookAsync(string path);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookService/WriteBook", ReplyAction="http://tempuri.org/IBookService/WriteBookResponse")]
        void WriteBook(Prac3_MVC.ServiceReference1.Book[] books, string path);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookService/WriteBook", ReplyAction="http://tempuri.org/IBookService/WriteBookResponse")]
        System.Threading.Tasks.Task WriteBookAsync(Prac3_MVC.ServiceReference1.Book[] books, string path);
        
        // CODEGEN: Generating message contract since the wrapper name (BookPurchaseInfo) of message BookPurchaseInfo does not match the default value (PurchaseBooks)
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookService/PurchaseBooks", ReplyAction="http://tempuri.org/IBookService/PurchaseBooksResponse")]
        Prac3_MVC.ServiceReference1.BookPurchaseResponse PurchaseBooks(Prac3_MVC.ServiceReference1.BookPurchaseInfo request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookService/PurchaseBooks", ReplyAction="http://tempuri.org/IBookService/PurchaseBooksResponse")]
        System.Threading.Tasks.Task<Prac3_MVC.ServiceReference1.BookPurchaseResponse> PurchaseBooksAsync(Prac3_MVC.ServiceReference1.BookPurchaseInfo request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="BookPurchaseInfo", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class BookPurchaseInfo {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public decimal budget;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Collections.Generic.Dictionary<int, int> items;
        
        public BookPurchaseInfo() {
        }
        
        public BookPurchaseInfo(decimal budget, System.Collections.Generic.Dictionary<int, int> items) {
            this.budget = budget;
            this.items = items;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="BookPurchaseResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class BookPurchaseResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public string response;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool result;
        
        public BookPurchaseResponse() {
        }
        
        public BookPurchaseResponse(string response, bool result) {
            this.response = response;
            this.result = result;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBookServiceChannel : Prac3_MVC.ServiceReference1.IBookService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BookServiceClient : System.ServiceModel.ClientBase<Prac3_MVC.ServiceReference1.IBookService>, Prac3_MVC.ServiceReference1.IBookService {
        
        public BookServiceClient() {
        }
        
        public BookServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BookServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BookServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BookServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Prac3_MVC.ServiceReference1.Book[] ReadBook(string path) {
            return base.Channel.ReadBook(path);
        }
        
        public System.Threading.Tasks.Task<Prac3_MVC.ServiceReference1.Book[]> ReadBookAsync(string path) {
            return base.Channel.ReadBookAsync(path);
        }
        
        public void WriteBook(Prac3_MVC.ServiceReference1.Book[] books, string path) {
            base.Channel.WriteBook(books, path);
        }
        
        public System.Threading.Tasks.Task WriteBookAsync(Prac3_MVC.ServiceReference1.Book[] books, string path) {
            return base.Channel.WriteBookAsync(books, path);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Prac3_MVC.ServiceReference1.BookPurchaseResponse Prac3_MVC.ServiceReference1.IBookService.PurchaseBooks(Prac3_MVC.ServiceReference1.BookPurchaseInfo request) {
            return base.Channel.PurchaseBooks(request);
        }
        
        public string PurchaseBooks(decimal budget, System.Collections.Generic.Dictionary<int, int> items, out bool result) {
            Prac3_MVC.ServiceReference1.BookPurchaseInfo inValue = new Prac3_MVC.ServiceReference1.BookPurchaseInfo();
            inValue.budget = budget;
            inValue.items = items;
            Prac3_MVC.ServiceReference1.BookPurchaseResponse retVal = ((Prac3_MVC.ServiceReference1.IBookService)(this)).PurchaseBooks(inValue);
            result = retVal.result;
            return retVal.response;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Prac3_MVC.ServiceReference1.BookPurchaseResponse> Prac3_MVC.ServiceReference1.IBookService.PurchaseBooksAsync(Prac3_MVC.ServiceReference1.BookPurchaseInfo request) {
            return base.Channel.PurchaseBooksAsync(request);
        }
        
        public System.Threading.Tasks.Task<Prac3_MVC.ServiceReference1.BookPurchaseResponse> PurchaseBooksAsync(decimal budget, System.Collections.Generic.Dictionary<int, int> items) {
            Prac3_MVC.ServiceReference1.BookPurchaseInfo inValue = new Prac3_MVC.ServiceReference1.BookPurchaseInfo();
            inValue.budget = budget;
            inValue.items = items;
            return ((Prac3_MVC.ServiceReference1.IBookService)(this)).PurchaseBooksAsync(inValue);
        }
    }
}
